### ISSUE TITLE
Mutual TLS

### ISSUE THREAD

**Issue by andrewbanchich** [jbr/tide-tls#10]
Are there any plans to support mTLS?

**Comment by jbr** [comment]
If I understand mTLS correctly, rustls does support this and therefore so do we. You'd want to use [TlsListenerBuilder::config](https://docs.rs/tide-rustls/0.2.0/tide_rustls/struct.TlsListenerBuilder.html#method.config) and build your own [rustls::ServerConfig](https://docs.rs/rustls/0.19.0/rustls/struct.ServerConfig.html) that includes client cert verification

**Comment by andrewbanchich** [comment]
I looked through the docs and I'm not familiar enough with that side of things to figure out how to do this. I'd like to have a higher level API that lets me give it a CA public key and trust all certs that CA has issued. Either that, or a PEM which contains all the certs the server should trust.

Something at that level would be really useful, and others in the `async-std` Discord have said they're interested in this as well.

**Comment by jbr** [comment]
I think that would be an issue to open on [async-tls](https://github.com/async-rs/async-tls) or rustls itself. This crate is intended just to be a small adapter on top of async-tls

**Comment by andrewbanchich** [comment]
Okay, thanks!
