### ISSUE TITLE
the trait bound tide_rustls::TlsListenerBuilder<_>: tide::listener::ToListener<()> is not satisfied

### ISSUE THREAD

**Issue by jeff-arn** [jbr/tide-tls#11]
# Version used

```toml
tide = "0.16.0"
tide-rustls = "0.2.0"
```

# Description

When running the example provided, I'm getting the trait bound error mentioned in the title, specifically:

```
the trait bound `tide_rustls::TlsListenerBuilder<_>: tide::listener::ToListener<()>` is not satisfied

the trait `tide::listener::ToListener<()>` is not implemented for `tide_rustls::TlsListenerBuilder<_>`
```

## Code example

Here is the code I'm using to implement:

```rust
#[async_std::main]
async fn main() -> tide::Result<()> {
    let mut test_app = tide::new();
    test_app.at("/").get(|_| async { Ok("test") });

    let test_listener = TlsListener::build()
        .addrs("0.0.0.0:4000")
        .cert(std::env::var("SERVER_CERT_PATH").unwrap())
        .key(std::env::var("SERVER_KEY_PATH").unwrap())
        .finish();

    app.listen(listener).await?;

    Ok(())
}
```

# Disclaimer

I am a rust novice, and so the likelihood of this being user error is very high, however, I wanted to post here in the event that there is a new trait from `tide` that needs to be implemented for recent versions.

**Comment by jeff-arn** [comment]
One observation as I've been testing this out is that when declaring the listener inline with the `app.listen()` call, it appears to compile, but when declaring the listener separately and calling `.finish()`, it throws the trait bound error mentioned in the issue.

For example, this code compiles with all of the above versions:

```rust
...

    let mut test_app = tide::new();
    test_app.at("/").get(|_| async { Ok("test") });

    test_app.listen(
        TlsListener::build()
            .addrs("0.0.0.0:4000")
            .cert(std::env::var("SERVER_CERT_PATH").unwrap())
            .key(std::env::var("SERVER_KEY_PATH").unwrap()),
    )
    .await?;

    Ok(())
 ```

**Comment by jbr** [comment]
I think the issue is that [finish](https://docs.rs/tide-rustls/0.2.0/tide_rustls/struct.TlsListenerBuilder.html#method.finish) returns a Result, so you need a ? after it. You can also skip the call to finish and pass the builder in to listen

**Comment by jeff-arn** [comment]
@jbr yes you are correct! I was attempting to use the wrapped Result! Thanks for the quick clarification. I'll close the issue.
